### ISSUE TITLE
Failing test: TimedEventTests

### ISSUE THREAD

**Issue by gerkey** [eProsima/Fast-RTPS#23]
This build:

http://ci.ros2.org/view/nightly/job/nightly_osx/234/testReport/projectroot.test.unittest.rtps.resources/timedevent/TimedEventTests/

shows a test failure on OSX for TimedEventTests. The tail end of the console output is:

~~~
[ RUN      ] TimedEvent.EventNonAutoDestruct_AutoRestart
[       OK ] TimedEvent.EventNonAutoDestruct_AutoRestart (10521 ms)
[ RUN      ] TimedEvent.EventNonAutoDestruc_AutoRestartAndDeleteRandomly
libc++abi.dylib: Pure virtual function called!
~~~

Looks like the program is crashing. Let us know if you need help reproducing it.

**Comment by richiprosima** [comment]
We fixed an invalid read detected by valgrind in the tests that may be related with your failure. We don't use OSX and never had that failture. Can you check it again with commit ca6d226? Thanks

**Comment by gerkey** [comment]
We're still seeing the failure on OSX. E.g., from a build yesterday:

http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/238/testReport/projectroot.test.unittest.rtps.resources/timedevent/TimedEventTests/

Interestingly, it doesn't always fail. Here's a build from the previous day where that test passed:

http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/237/testReport/projectroot.test.unittest.rtps.resources/timedevent/TimedEventTests/

**Comment by richiprosima** [comment]
I found an error in test TimedEventTests. And yes, it's was a random error.

**Comment by gerkey** [comment]
That fix looks very promising, thanks. I'll report back after we've had a couple of days of nightly test runs.

**Comment by gerkey** [comment]
It looks like the problem is fixed for Release and "none" build types, which is great!

Now we have a different failure from OSX built in Debug: http://ci.ros2.org/view/nightly/job/nightly_osx_debug/6/testReport/projectroot.test.unittest.rtps.resources/timedevent/TimedEventTests/. The error:

~~~
[ RUN      ] TimedEvent.EventNonAutoDestruc_AutoRestartAndDeleteRandomly
Assertion failed: (!res), function ~mutex, file /usr/local/include/boost/thread/pthread/mutex.hpp, line 111.
Assertion failed: (!pthread_mutex_lock(m)), function pthread_mutex_scoped_lock, file /usr/local/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp, line 26.
~~~

**Comment by richiprosima** [comment]
I've shown that and i'm working on it.

**Comment by richiprosima** [comment]
Solved last issue in TimedEventTests.

**Comment by gerkey** [comment]
Indeed, that failure didn't occur in any of our builds from last night. Thanks!
